services:
  web:
    build: .
    container_name: task_web
    image: task_project:latest
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
   
  db:
    image: postgres:15
    restart: always
    container_name: postgres_container
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

 
networks:
  app_network:
    driver: bridge

volumes:
  postgres-data: