name: Lint Python Code

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with Python 3.11
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install

      - name: Run flake8
        run: |
          poetry run flake8 . 

      - name: Run black (check mode)
        run: |
          poetry run black --check .
